# Generated by Django 4.1.1 on 2022-09-25 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tango', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='nationality',
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
