# Generated by Django 4.1.1 on 2022-09-25 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tango', '0004_order_customer_order_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='tag',
            field=models.ManyToManyField(to='tango.producttag'),
        ),
    ]
